import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Maige | AI Issue Labeller</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col items-center justify-center space-y-6 bg-black">
        <h1 className="text-8xl font-bold tracking-tight text-white">Maige</h1>
        <h2 className="text-3xl font-semibold tracking-tight text-white/80">
          Let GPT label your issues.
        </h2>
        <p className="pb-8 italic text-white/60">Magically.</p>
        <Link href="https://github.com/apps/maige-bot">
          <button className="rounded-md border-gray-900 bg-green-600 px-6 py-3 font-medium text-white">
            Install with GitHub
          </button>
        </Link>
      </main>
    </>
  );
};

export default Home;
